# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Minha_HQ_Preferida' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minha_HQ_Preferida
  pod 'Alamofire', '~> 5.4'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'

end
